const REGION_SD = {
  "REQUEST_TIME": 0,

  "UNLOAD_TIME": 1,
  "DATA_ATTACHED": 2,

  "MAIN_THREAD_RECEIVED": 3,
  "LOADED": 4,
  "LOAD_ACKNOWLEDGED": 5,
  "GD_REQUIRED": 6,
  "GD_UPDATE_REQUIRED": 7,
  "REVERSE_DATA_ACKNOWLEDGED": 8,

  "REGION_X": 9,
  "REGION_Y": 10,
  "REGION_Z": 11,
  "DEPTH": 12,

  "IS_ENTIRELY_SOLID": 13,
  "COMMON_BLOCK": 14,

  "LOADING_STAGE": 15,

  "BUFFER_SIZE": 16 * 8
};

export default REGION_SD;
